import Link from "next/link";
import { prisma } from "@/lib/prisma";

export const dynamic = "force-dynamic";

export default async function ReportsPage() {
  const reports = await prisma.report.findMany({
    where: { subjectType: "candidate" },
    orderBy: { createdAt: "desc" },
    take: 100,
  });

  return (
    <div>
      <div className="mb-8">
        <div className="eyebrow">Archive</div>
        <h1 className="text-3xl font-semibold">Reports</h1>
        <p className="text-[var(--color-text-mid)] text-sm mt-2">
          Investment memos generated by the committee. {reports.length} total.
        </p>
      </div>

      {reports.length === 0 ? (
        <div className="empty-state">
          <div className="empty-icon">◌</div>
          <h3>No reports yet</h3>
          <p className="text-[var(--color-text-mid)] text-sm mt-2">
            Reports appear here after the committee evaluates a candidate.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {reports.map((r) => {
            const json = (r.reportJson ?? {}) as Record<string, unknown>;
            const starRating = r.starRating ?? (json.star_rating as number | undefined);
            const summary =
              (json.executive_summary as string | undefined) ??
              (json.startup_overview as string | undefined) ??
              "No summary available.";

            return (
              <Link
                key={r.id}
                href={`/dashboard/reports/${r.id}`}
                className="panel block hover:border-[var(--color-teal)] transition-colors"
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="min-w-0 flex-1">
                    <h3 className="font-semibold truncate">
                      {r.company ?? "Unknown company"}
                    </h3>
                    <div className="flex items-center gap-3 mt-1 text-xs text-[var(--color-text-low)] font-mono">
                      <span>{r.createdAt.toISOString().slice(0, 10)}</span>
                      {typeof r.weightedScore === "number" && (
                        <span>score: {r.weightedScore.toFixed(2)}/10</span>
                      )}
                    </div>
                    <p className="text-sm text-[var(--color-text-mid)] mt-3 line-clamp-2">
                      {summary}
                    </p>
                  </div>
                  <div className="flex flex-col items-end gap-2 flex-shrink-0">
                    {r.decision && (
                      <span
                        className={
                          r.decision === "INVEST"
                            ? "badge-invest"
                            : "badge-pass"
                        }
                      >
                        {r.decision}
                      </span>
                    )}
                    {typeof starRating === "number" && (
                      <span className="text-xs text-[var(--color-amber)]">
                        {"★".repeat(starRating)}
                        {"☆".repeat(5 - starRating)}
                      </span>
                    )}
                  </div>
                </div>
              </Link>
            );
          })}
        </div>
      )}
    </div>
  );
}